version: '3.8'

services:

  servidor1:
    build: .
    container_name: servidor1
    hostname: servidor1
    ports:
      - "2221:22"


  servidor2:
    build:
      context: .
    container_name: servidor2
    hostname: servidor2
    ports:
      - "2232:22"

  servidor3:
    build: .
    container_name: servidor3
    hostname: servidor3
    ports:
      - "2223:22"

  servidor4:
    build: .
    container_name: servidor4
    hostname: servidor4
    ports:
      - "2224:22"

  servidor5:
    build: .
    container_name: servidor5
    hostname: servidor5
    ports:
      - "2225:22"