name: CI/CD Docker Hub

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Construir y publicar imagen Docker
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/ansible-docker:latest .

      - name: Publicar imagen en Docker Hub
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/ansible-docker:latest